import re
from subprocess import Popen, PIPE
worlds = [
'oldschool5.runescape.com',
'oldschool6.runescape.com',
'oldschool7.runescape.com',
'oldschool13.runescape.com',
'oldschool14.runescape.com',
'oldschool15.runescape.com',
'oldschool19.runescape.com',
'oldschool20.runescape.com',
'oldschool21.runescape.com',
'oldschool22.runescape.com',
'oldschool23.runescape.com',
'oldschool24.runescape.com',
'oldschool29.runescape.com',
'oldschool30.runescape.com',
'oldschool31.runescape.com',
'oldschool32.runescape.com',
'oldschool38.runescape.com',
'oldschool39.runescape.com',
'oldschool40.runescape.com',
'oldschool46.runescape.com',
'oldschool47.runescape.com',
'oldschool48.runescape.com',
'oldschool53.runescape.com',
'oldschool54.runescape.com',
'oldschool55.runescape.com',
'oldschool56.runescape.com',
'oldschool57.runescape.com',
'oldschool61.runescape.com',
'oldschool62.runescape.com',
'oldschool74.runescape.com',
'oldschool77.runescape.com',
'oldschool78.runescape.com',
'oldschool115.runescape.com',
'oldschool116.runescape.com',
'oldschool120.runescape.com',
'oldschool121.runescape.com',
'oldschool122.runescape.com',
'oldschool128.runescape.com',
'oldschool129.runescape.com',
'oldschool143.runescape.com',
'oldschool144.runescape.com',
'oldschool145.runescape.com',
'oldschool146.runescape.com',
'oldschool177.runescape.com',
'oldschool178.runescape.com',
'oldschool179.runescape.com',
'oldschool180.runescape.com',
'oldschool181.runescape.com',
'oldschool182.runescape.com',
'oldschool184.runescape.com',
'oldschool185.runescape.com',
'oldschool186.runescape.com',
'oldschool187.runescape.com',
'oldschool188.runescape.com',
'oldschool189.runescape.com',
'oldschool190.runescape.com',
'oldschool191.runescape.com',
'oldschool192.runescape.com',
'oldschool193.runescape.com',
'oldschool194.runescape.com',
'oldschool195.runescape.com',
'oldschool196.runescape.com'
]
worldnums = [
'World 305',
'World 306',
'World 307',
'World 313',
'World 314',
'World 315',
'World 319',
'World 320',
'World 321',
'World 322',
'World 323',
'World 324',
'World 329',
'World 330',
'World 331',
'World 332',
'World 338',
'World 339',
'World 340',
'World 346',
'World 347',
'World 348',
'World 353',
'World 354',
'World 355',
'World 356',
'World 357',
'World 361',
'World 362',
'World 374',
'World 377',
'World 378',
'World 415',
'World 416',
'World 420',
'World 421',
'World 422',
'World 428',
'World 429',
'World 443',
'World 444',
'World 445',
'World 446',
'World 477',
'World 478',
'World 479',
'World 480',
'World 481',
'World 482',
'World 484',
'World 485',
'World 486',
'World 487',
'World 488',
'World 489',
'World 490',
'World 491',
'World 492',
'World 493',
'World 494',
'World 495',
'World 496'
]

def parser(worlds):
    returnlist = []
    for i in range(len(worlds)):
        strlatency = ''
        stdout = Popen('ping -n 1 ' + worlds[i], shell=True, stdout=PIPE).stdout
        output = str(stdout.read())
        if 'timed out' in output:
            returnlist.append(worldnums[i] + ' timed out')
            continue
        latency = re.findall("(?<=Minimum = )[0-9]{2,}", output)
        strlatency += str(latency[0])
        if int(strlatency) < 30:
            returnlist.append(strlatency + 'ms, ' + worldnums[i])
    return returnlist
output = parser(worlds)
output.sort()
for i in output:
    print(i)